return {
  -- belts
  'transport-belt',
  'fast-transport-belt',
  'express-transport-belt',
  -- undergrounds
  'underground-belt',
  'fast-underground-belt',
  'express-underground-belt',
  -- splitters
  'splitter',
  'fast-splitter',
  'express-splitter',
  -- pipes
  'pipe',
  'pipe-to-ground',
  -- poles
  'small-electric-pole',
  'medium-electric-pole',
  'big-electric-pole',
  'substation',
  -- drills
  'electric-mining-drill',
  'burner-mining-drill',
  'pumpjack',
  -- vehicles
  'car',
  'tank',
  'spidertron',
  -- rails
  'straight-rail',
  'curved-rail',
  'rail-signal',
  'rail-chain-signal',
  'train-stop',
  'locomotive',
  'cargo-wagon',
  'fluid-wagon',
  'artillery-wagon',
  -- inserters
  'burner-inserter',
  'inserter',
  'long-handed-inserter',
  'fast-inserter',
  'bulk-inserter',
  -- Py drills
  'aluminium-mine',
  'antimonium-drill-mk01',
  'antimonium-drill-mk02',
  'antimonium-drill-mk03',
  'antimonium-drill-mk04',
  'bitumen-seep-mk01',
  'bitumen-seep-mk02',
  'bitumen-seep-mk03',
  'bitumen-seep-mk04',
  'borax-mine-mk02',
  'borax-mine-mk03',
  'borax-mine-mk04',
  'borax-mine',
  'chromium-mine',
  'coal-mine',
  'collector-mk02',
  'collector-mk03',
  'collector-mk04',
  'collector',
  'copper-mine',
  'diamond-mine',
  'fluid-drill-mk01',
  'fluid-drill-mk02',
  'fluid-drill-mk03',
  'fluid-drill-mk04',
  'geothermal-plant-mk01',
  'harvester',
  'iron-mine',
  'lead-mine',
  'mo-mine',
  'natural-gas-extractor-mk01',
  'natural-gas-extractor-mk02',
  'natural-gas-extractor-mk03',
  'natural-gas-extractor-mk04',
  'natural-gas-seep-mk01',
  'natural-gas-seep-mk02',
  'natural-gas-seep-mk03',
  'natural-gas-seep-mk04',
  'nexelit-mine',
  'nickel-mine',
  'niobium-mine',
  'oil-derrick-mk01',
  'oil-derrick-mk02',
  'oil-derrick-mk03',
  'oil-derrick-mk04',
  'oil-sand-extractor-mk01',
  'oil-sand-extractor-mk02',
  'oil-sand-extractor-mk03',
  'oil-sand-extractor-mk04',
  'phosphate-mine-02',
  'phosphate-mine',
  'quartz-mine',
  'rare-earth-mine',
  'ree-mining-drill-mk01',
  'ree-mining-drill-mk02',
  'ree-mining-drill-mk03',
  'ree-mining-drill-mk04',
  'regolite-mine',
  'salt-mine',
  'sulfur-mine',
  'tar-extractor-mk01',
  'tar-extractor-mk02',
  'tar-extractor-mk03',
  'tar-extractor-mk04',
  'tar-seep-mk01',
  'tar-seep-mk02',
  'tar-seep-mk03',
  'tar-seep-mk04',
  'tin-mine',
  'titanium-mine',
  'uranium-mine',
  'zinc-mine',
  -- Py Industry
  'mk02-locomotive',
  'mk02-wagon',
  'mk02-fluid-wagon',
  'niobium-pipe',
  'niobium-pipe-to-ground',
  -- Py High Tech
  'ht-pipes',
  'ht-pipes-to-ground',
  'ht-locomotive',
  'ht-generic-wagon',
  'ht-generic-fluid-wagon',
  -- Py Alternative Energy
  'nexelit-power-pole',
  'nexelit-substation',
  'mk04-locomotive',
  'mk04-wagon',
  'mk04-fluid-wagon',
}
