branches:
    # Ignore pull requests to the named branches
    ignore:
        - 'live_testing'
        - 'maps/biter_lane_wars'
linters:
    luacheck:
        config: '.luacheckrc'
review:
    # Don't use 'failure' build status when
    # a pull request contains style errors.
    fail_on_comments: true
