global.scenario = {}
global.scenario.variables = {}
global.scenario.variables.time_set_moment = 0
global.scenario.variables.current_month = 1
global.scenario.variables.current_day = 1
global.scenario.variables.current_h = 0
global.scenario.variables.current_m = 0
global.scenario.variables.days_passed = 0
global.scenario.variables.mods = require "locale.resources.mods"
global.scenario.variables.regulars = require "locale.resources.regulars"
global.scenario.variables.player_positions = {}
global.scenario.variables.player_walk_distances = {}
global.scenario.config = {}
global.scenario.custom_functions = {}
global.scenario.config.nuke_min_time_hours = 3 --how long a player must be on the server to be allowed to use the nuke
