_DEBUG = false
MARKET_ITEM = 'coin'

global.scenario = {}
global.scenario.variables = {}
global.scenario.variables.player_positions = {}
global.player_walk_distances = {}
global.scenario.variables.player_deaths = {}
global.scenario.config = {}
global.scenario.config.player_list = {}
global.scenario.config.player_list.enable_coin_col = true
global.scenario.config.paint = {}
global.scenario.config.paint.enable = true
global.scenario.config.fish_market = {}
global.scenario.config.fish_market.enable = true
global.scenario.config.nuke_control = {}
global.scenario.config.nuke_control.enable_autokick = true
global.scenario.config.nuke_control.enable_autoban = true
global.scenario.custom_functions = {}
global.scenario.config.nuke_control.nuke_min_time_hours = 3 --how long a player must be on the server to be allowed to use the nuke
global.newline = '\n'
newline = '\n'
