-- If you're looking for a map's name, you're in the right place!
local maps = {
    'antfarm',
    'bacon_islands',
    'beach',
    'borg_planet_v2',
    'broken_web',
    'connected_dots',
    'contra_spiral',
    'cookies',
    'crash_site',
    'creation_of_adam',
    'creation_of_adam2',
    'crosses',
    'crosses3',
    'dagobah_swamp',
    'danger_ores',
    'diagonal_lattice',
    'diagonal_ribbon',
    'dickbutt',
    'diggy',
    'dimensions',
    'dino_island',
    'dna',
    'donut',
    'double_beach',
    'factorio_logo',
    'factorio_logo2',
    'factory',
    'fish_islands',
    'fractal_balls',
    'fruit_loops',
    'gears',
    'goat',
    'goats_on_goats',
    'GoT',
    'grid_islands',
    'grid_islands_rotated',
    'hearts',
    'honeycomb',
    'hub_spiral',
    'infinite_mazes',
    'island_resort',
    'left',
    'line_and_tree',
    'line_and_trees',
    'lines',
    'lines_and_balls',
    'lines_and_squares',
    'maltease_crossings',
    'manhattan',
    'maori',
    'maze',
    'misc_stuff',
    'mobius_strip',
    'mona_lisa',
    'pacman',
    'plus',
    'red_planet_v2',
    'right',
    'rotten_apples',
    'spiral',
    'spiral_crossings',
    'spiral_of_spirals',
    'spiral_tri',
    'spiral2',
    'spiral3',
    'square_spiral',
    'template',
    'tetris',
    'threaded_spirals',
    'toxic_danger_ore_jungle',
    'toxic_jungle',
    'triangle_of_death',
    'turkey',
    'UK',
    'up',
    'vanilla',
    'venice',
    'venus',
    'void_gears',
    'women',
    'world_map',
    'world_map_thanksgiving',
    'x_shape',
    'test',
    'meteor_strike', -- unfinished
    'web', --unfinished
    'rings_and_boxes', --unfinished
    'ring_of_balls', --unfinished
    'turkey', -- needs to be rebuilt from missing source image.
    'north_america', -- needs to be rebuilt from missing source image.
}
return maps
