return {
    {
        name = 'temporary-running-speed-bonus',
        name_label = 'Temporary running speed bonus',
        type = 'temporary-buff',
        description = 'Increases running speed by one level for a short period',
        sprite = 'technology/exoskeleton-equipment',
        stack_limit = 1,
        price = 10,
    },
    {
        name = 'temporary-mining-speed-bonus',
        name_label = 'Temporary mining speed bonus',
        type = 'temporary-buff',
        description = 'Increases manual mining speed by one level for a short period',
        sprite = 'technology/mining-productivity-1',
        stack_limit = 1,
        price = 10,
    },
    {price = 2,    name = 'raw-fish'},
    {price = 0.95, name = 'rail'},
    {price = 2,    name = 'rail-signal'},
    {price = 2,    name = 'rail-chain-signal'},
    {price = 15,   name = 'train-stop'},
    {price = 75,   name = 'locomotive'},
    {price = 30,   name = 'cargo-wagon'},
    {price = 0.95, name = 'red-wire'},
    {price = 0.95, name = 'green-wire'},
    {price = 3,    name = 'decider-combinator'},
    {price = 3,    name = 'arithmetic-combinator'},
    {price = 3,    name = 'constant-combinator'},
    {price = 7,    name = 'programmable-speaker'},
    {price = 15,   name = 'submachine-gun'},
    {price = 15,   name = 'shotgun'},
    {price = 250,  name = 'combat-shotgun'},
    {price = 25,   name = 'railgun'},
    {price = 250,  name = 'flamethrower'},
    {price = 175,  name = 'rocket-launcher'},
    {price = 250,  name = 'tank-cannon'},
    {price = 750,  name = 'tank-machine-gun'},
    {price = 75,   name = 'tank-flamethrower'},
    {price = 2500, name = 'artillery-wagon-cannon'},
    {price = 1,    name = 'firearm-magazine'},
    {price = 5,    name = 'piercing-rounds-magazine'},
    {price = 20,   name = 'uranium-rounds-magazine'},
    {price = 2,    name = 'shotgun-shell'},
    {price = 10,   name = 'piercing-shotgun-shell'},
    {price = 5,    name = 'railgun-dart'},
    {price = 25,   name = 'flamethrower-ammo'},
    {price = 15,   name = 'rocket'},
    {price = 25,   name = 'explosive-rocket'},
    {price = 2500, name = 'atomic-bomb'},
    {price = 20,   name = 'cannon-shell'},
    {price = 30,   name = 'explosive-cannon-shell'},
    {price = 75,   name = 'explosive-uranium-cannon-shell'},
    {price = 100,  name = 'artillery-shell'},
    {price = 3,    name = 'land-mine'},
    {price = 5,    name = 'grenade'},
    {price = 35,   name = 'cluster-grenade'},
    {price = 5,    name = 'defender-capsule'},
    {price = 75,   name = 'destroyer-capsule'},
    {price = 35,   name = 'poison-capsule'},
    {price = 35,   name = 'slowdown-capsule'},
    {price = 50,   name = 'artillery-targeting-remote'},
    {price = 1000, name = 'artillery-turret'},
    {price = 350,  name = 'modular-armor'},
    {price = 875,  name = 'power-armor'},
    {price = 40,   name = 'solar-panel-equipment'},
    {price = 875,  name = 'fusion-reactor-equipment'},
    {price = 100,  name = 'battery-equipment'},
    {price = 625,  name = 'battery-mk2-equipment'},
    {price = 250,  name = 'belt-immunity-equipment'},
    {price = 100,  name = 'night-vision-equipment'},
    {price = 150,  name = 'exoskeleton-equipment'},
    {price = 250,  name = 'personal-roboport-equipment'},
    {price = 25,   name = 'construction-robot'},
    {price = 350,  name = 'energy-shield-equipment'},
    {price = 750,  name = 'personal-laser-defense-equipment'},
    {price = 1,    name = 'refined-hazard-concrete'},
}
