return {
    {
        price = {{'coin', 10}},
        offer = {type = 'nothing', effect_description = 'Temporary speed bonus - Price 10  Fish'}
    },
    {
        price = {{'coin', 10}},
        offer = {type = 'nothing', effect_description = 'Temporary mining bonus - Price 10  Fish'}
    },
    {price = {{'coin', 2}}, offer = {type = 'give-item', item = 'raw-fish'}},
    {price = {{'coin', 15}}, offer = {type = 'give-item', item = 'steel-axe'}},
    {price = {{'coin', 15}}, offer = {type = 'give-item', item = 'submachine-gun'}},
    {price = {{'coin', 15}}, offer = {type = 'give-item', item = 'shotgun'}},
    {price = {{'coin', 250}}, offer = {type = 'give-item', item = 'combat-shotgun'}},
    {price = {{'coin', 25}}, offer = {type = 'give-item', item = 'railgun'}},
    {price = {{'coin', 250}}, offer = {type = 'give-item', item = 'flamethrower'}},
    {price = {{'coin', 175}}, offer = {type = 'give-item', item = 'rocket-launcher'}},
    {price = {{'coin', 250}}, offer = {type = 'give-item', item = 'tank-cannon'}},
    {price = {{'coin', 750}}, offer = {type = 'give-item', item = 'tank-machine-gun'}},
    {price = {{'coin', 75}}, offer = {type = 'give-item', item = 'tank-flamethrower'}},
    {price = {{'coin', 2500}}, offer = {type = 'give-item', item = 'artillery-wagon-cannon'}},
    {price = {{'coin', 1}}, offer = {type = 'give-item', item = 'firearm-magazine'}},
    {price = {{'coin', 5}}, offer = {type = 'give-item', item = 'piercing-rounds-magazine'}},
    {price = {{'coin', 20}}, offer = {type = 'give-item', item = 'uranium-rounds-magazine'}},
    {price = {{'coin', 2}}, offer = {type = 'give-item', item = 'shotgun-shell'}},
    {price = {{'coin', 10}}, offer = {type = 'give-item', item = 'piercing-shotgun-shell'}},
    {price = {{'coin', 5}}, offer = {type = 'give-item', item = 'railgun-dart'}},
    {price = {{'coin', 25}}, offer = {type = 'give-item', item = 'flamethrower-ammo'}},
    {price = {{'coin', 15}}, offer = {type = 'give-item', item = 'rocket'}},
    {price = {{'coin', 25}}, offer = {type = 'give-item', item = 'explosive-rocket'}},
    {price = {{'coin', 2500}}, offer = {type = 'give-item', item = 'atomic-bomb'}},
    {price = {{'coin', 20}}, offer = {type = 'give-item', item = 'cannon-shell'}},
    {price = {{'coin', 30}}, offer = {type = 'give-item', item = 'explosive-cannon-shell'}},
    {price = {{'coin', 75}}, offer = {type = 'give-item', item = 'explosive-uranium-cannon-shell'}},
    {price = {{'coin', 100}}, offer = {type = 'give-item', item = 'artillery-shell'}},
    {price = {{'coin', 1}}, offer = {type = 'give-item', item = 'land-mine'}},
    {price = {{'coin', 5}}, offer = {type = 'give-item', item = 'grenade'}},
    {price = {{'coin', 35}}, offer = {type = 'give-item', item = 'cluster-grenade'}},
    {price = {{'coin', 5}}, offer = {type = 'give-item', item = 'defender-capsule'}},
    --{price = {{'coin', 15}}, offer = {type = 'give-item', item = 'distractor-capsule'}}, Removed so we dont have 51 items and they are useless anyways
    {price = {{'coin', 75}}, offer = {type = 'give-item', item = 'destroyer-capsule'}},
    {price = {{'coin', 35}}, offer = {type = 'give-item', item = 'poison-capsule'}},
    {price = {{'coin', 35}}, offer = {type = 'give-item', item = 'slowdown-capsule'}},
    {price = {{'coin', 50}}, offer = {type = 'give-item', item = 'artillery-targeting-remote'}},
    {price = {{'coin', 1000}}, offer = {type = 'give-item', item = 'artillery-turret'}},
    {price = {{'coin', 350}}, offer = {type = 'give-item', item = 'modular-armor'}},
    {price = {{'coin', 875}}, offer = {type = 'give-item', item = 'power-armor'}},
    {price = {{'coin', 40}}, offer = {type = 'give-item', item = 'solar-panel-equipment'}},
    {price = {{'coin', 875}}, offer = {type = 'give-item', item = 'fusion-reactor-equipment'}},
    {price = {{'coin', 100}}, offer = {type = 'give-item', item = 'battery-equipment'}},
    {price = {{'coin', 625}}, offer = {type = 'give-item', item = 'battery-mk2-equipment'}},
    {price = {{'coin', 250}}, offer = {type = 'give-item', item = 'belt-immunity-equipment'}},
    {price = {{'coin', 100}}, offer = {type = 'give-item', item = 'night-vision-equipment'}},
    {price = {{'coin', 150}}, offer = {type = 'give-item', item = 'exoskeleton-equipment'}},
    {price = {{'coin', 250}}, offer = {type = 'give-item', item = 'personal-roboport-equipment'}},
    {price = {{'coin', 25}}, offer = {type = 'give-item', item = 'construction-robot'}},
    {price = {{'coin', 350}}, offer = {type = 'give-item', item = 'energy-shield-equipment'}},
    {price = {{'coin', 350}}, offer = {type = 'give-item', item = 'personal-laser-defense-equipment'}},
    {price = {{'coin', 1}}, offer = {type = 'give-item', item = 'refined-hazard-concrete'}},
    {price = {{'coin', 75}}, offer = {type = 'give-item', item = 'loader'}},
    {price = {{'coin', 150}}, offer = {type = 'give-item', item = 'fast-loader'}},
    {price = {{'coin', 225}}, offer = {type = 'give-item', item = 'express-loader'}},

    --[[ {price = {{'coin', 5}}, offer = {type = 'give-item', item = 'science-pack-1'}},
    {price = {{'coin', 10}}, offer = {type = 'give-item', item = 'science-pack-2'}},
    {price = {{'coin', 15}}, offer = {type = 'give-item', item = 'science-pack-3'}},
    {price = {{'coin', 15}}, offer = {type = 'give-item', item = 'military-science-pack'}},
    {price = {{'coin', 20}}, offer = {type = 'give-item', item = 'production-science-pack'}},
    {price = {{'coin', 25}}, offer = {type = 'give-item', item = 'high-tech-science-pack'}}, ]]
}
