return {
    '99 Red Balloons',
    'A Team with No Name',
    'Amigos',
    'Attack of the Invisible Ninja',
    'Bed Bath and Beyonce',
    'Beer Makes Smart',
    'Big Dudes Scared Shoes',
    'Boomers',
    'Car Insurance Mafia',
    'Civil Disobedients',
    'Corporate Punishment',
    'Dangerous Divas',
    'Dangerous Rocks',
    'Daring Dinosaurs',
    'Dark Angels',
    'Dark Thunder',
    'Darling Angels',
    'Dream Crushers',
    'Estrogen Express',
    'Evil League of Evil',
    'Fabulous Fairies',
    'Fargo Woodchippers',
    'Flying Squirrels',
    'Free Mountain of Muscle',
    'Game of Drones',
    'Golden Bears',
    'Gorillas In the Mist',
    'Gossip Geese',
    'Hairy Backs Anonymous',
    'Hustlin’ Owls',
    'Hustlin’ Quakers',
    'Introverted Extroverts',
    'Jaguars',
    'Land Sharks',
    'Lemon Drops',
    'Loons',
    'Mad Thrashers',
    'Magnificent Maniacs',
    'Man-Chest-Hair United',
    'Mean Green',
    'Menace to Sobriety',
    'Mighty Mountain Diggers',
    'Mostly Harmless',
    'Mud Hens',
    'Mule Riders',
    'Mullet Mafia',
    'Murder of Crows',
    'Nerd Herd',
    'Netflix and Chill',
    'Not Fast But Furious',
    'Not Last Place',
    'Orioles',
    'Periodic Farters',
    'Pink Dragons',
    'Pink Pandas',
    'Priceless Pythons',
    'Procrastinators',
    'Psychodelic Hurricanes',
    'Purple People Eaters',
    'Ragin’ Cajuns',
    'Railsplitters',
    'Rainbow Unicorns',
    'Rainbow Warriors',
    'Razzle Dazzle',
    'Red Dragons',
    'Red Gophers',
    'Red Raiders',
    'Run Like the Winded',
    'Running On Empty',
    'Sausage Factory',
    'Scarlet Raptors',
    'Screaming Eagles',
    'Seawolves',
    'Shapeshifters',
    'Silverswords',
    'Skyhawks',
    'Smooth Operators',
    'Snickerdoodles',
    'Soul Spartans',
    'Soul Train Riders',
    'Southern Discomfort',
    'Spaghetti Legs',
    'Spicy Mustard',
    'Stinky Cheese',
    'Teenage Dirtbags',
    'Tequila Mockingbird',
    'The Baha Badboys',
    'The Big Egos',
    'The Buffalo Wings',
    'The Creeping Spiders',
    'The Crusty Crusaders',
    'The Curse',
    'The Diplomatic Cowboys',
    'The Electric Force',
    'The Fast and the Curious',
    'The Fat Pirates',
    'The Has-Beens',
    'The Human Targets',
    'The Knights Who Say Ni',
    'The Last Place Lolipops',
    'The London Silly Nannies',
    'The Mystery Machine',
    'The Pace Makers',
    'The Puppet Masters',
    'The Scuba Squad',
    'The Silly Squids',
    'The Tater Tots',
    'The Team Team',
    'The Teenie Weenies',
    'The Walkie Talkies',
    'The Weed Whackers!',
    'Thundering Herd',
    'ThunderWolves',
    'Timberwolves',
    'Titans',
    'Trojans',
    'Underachievers',
    'Vandals',
    'Warhawks',
    'Wasted Potential',
    'We Showed Up',
    'We Talk A Lot',
    'Wild Kittens',
    'Worse Than Nickleback',
    'Young Tarts and Old Farts'
}
