return {
  {
    name = 'temporary-running-speed-bonus',
    name_label = {'market_items.running_speed_bonus_name_label'},
    type = 'temporary-buff',
    description = {'market_items.running_speed_bonus_description'},
    sprite = 'technology/exoskeleton-equipment',
    stack_limit = 1,
    price = 10,
  },
  {
    name = 'temporary-mining-speed-bonus',
    name_label = {'market_items.mining_speed_bonus_name_label'},
    type = 'temporary-buff',
    description = {'market_items.mining_speed_bonus_description'},
    sprite = 'technology/mining-productivity-1',
    stack_limit = 1,
    price = 10,
  },
  {price =     1, name = 'firearm-magazine'},
  {price =     1, name = 'land-mine'},
  {price =     1, name = 'wood'},
  {price =     2, name = 'rocket'},
  {price =     2, name = 'shotgun-shell'},
  {price =     3, name = 'cannon-shell'},
  {price =     4, name = 'defender-capsule'},
  {price =     4, name = 'piercing-rounds-magazine'},
  {price =     5, name = 'raw-fish'},
  {price =     6, name = 'piercing-shotgun-shell'},
  {price =     7, name = 'explosive-cannon-shell'},
  {price =     7, name = 'explosive-rocket'},
  {price =     8, name = 'grenade'},
  {price =    10, name = 'artillery-shell'},
  {price =    10, name = 'light-armor'},
  {price =    25, name = 'cliff-explosives'},
  {price =    25, name = 'flamethrower-ammo'},
  {price =    30, name = 'submachine-gun'},
  {price =    32, name = 'cluster-grenade'},
  {price =    35, name = 'construction-robot'},
  {price =    40, name = 'poison-capsule'},
  {price =    50, name = 'gun-turret'},
  {price =    50, name = 'solar-panel-equipment'},
  {price =    80, name = 'car'},
  {price =   100, name = 'battery-equipment'},
  {price =   125, name = 'heavy-armor'},
  {price =   125, name = 'night-vision-equipment'},
  {price =   125, name = 'rocket-launcher'},
  {price =   150, name = 'dungeon-support'},
  {price =   175, name = 'exoskeleton-equipment'},
  {price =   200, name = 'belt-immunity-equipment'},
  {price =   200, name = 'energy-shield-equipment'},
  {price =   250, name = 'combat-shotgun'},
  {price =   250, name = 'personal-roboport-equipment'},
  {price =   300, name = 'laser-turret'},
  {price =   350, name = 'modular-armor'},
  {price =   450, name = 'artillery-turret'},
  {price =   450, name = 'flamethrower'},
  {price =   625, name = 'battery-mk2-equipment'},
  {price =   850, name = 'personal-laser-defense-equipment'},
  {price =  1000, name = 'tunnel'},
  {price =  1200, name = 'tank'},
  {price =  1500, name = 'power-armor'},
  {price =  2250, name = 'fission-reactor-equipment'},
  {price =  7500, name = 'atomic-bomb'},
  {price = 12000, name = 'power-armor-mk2'},
}