return {
  -- belts
  'transport-belt',
  'fast-transport-belt',
  'express-transport-belt',
  -- undergrounds
  'underground-belt',
  'fast-underground-belt',
  'express-underground-belt',
  -- pipes
  'copper-pipe',
  'copper-pipe-to-ground',
  'copper-pipe-to-ground-short',
  'steam-pipe',
  'steam-pipe-to-ground',
  'steam-pipe-to-ground-short',
  'pipe',
  'pipe-to-ground',
  'pipe-to-ground-short',
  'air-pipe',
  'air-pipe-to-ground',
  'air-pipe-to-ground-short',
  -- poles
  'small-electric-pole',
  'medium-electric-pole',
  'big-electric-pole',
  'substation',
  'small-bronze-pole',
  'small-iron-pole',
  'big-wooden-pole',
  -- drills
  'electric-mining-drill',
  'burner-mining-drill',
  'pumpjack',
  'steam-drill',
  'chrome-drill',
  'copper-derrick',
  'steel-derrick',
  -- simulation (needed?)
  --'electric-mining-drill-simulation',
  --'steam-drill-simulation',
  --'chrome-drill-simulation',
  -- vehicles
  'car',
  'tank',
  'spidertron',
  'monowheel',
  'heavy-roller',
  'heavy-picket',
  -- rails
  'straight-rail',
  'curved-rail',
  'rail-signal',
  'rail-chain-signal',
  'train-stop',
  'locomotive',
  'cargo-wagon',
  'fluid-wagon',
  'artillery-wagon',
}
