-- this file contains all information related to map generation and control of new features.
-- a new feature will be enabled each hour, announced in chat and then never referenced again.
-- new_names.lua will have the player and tag names to fit in with the theme
-- icebergs.lua will contain all the features themselves
--no clue currently what mapgen should be, other than maybe a large iceberg?
