local b = require 'map_gen.shared.builders'
local start_value = b.euclidean_value(50, 0)
local value = b.exponential_value(0, 0.035, 1.45)

return {
    {
        name = 'coal',
        ['tiles'] = {
            [1] = 'volcanic-soil-dark',
            [2] = 'volcanic-soil-light',
            [3] = 'volcanic-ash-cracks',
            [4] = 'volcanic-ash-dark',
            [5] = 'volcanic-ash-flats',
            [6] = 'volcanic-ash-light',
            [7] = 'volcanic-ash-soil',
            [8] = 'volcanic-cracks',
            [9] = 'volcanic-cracks-hot',
            [10] = 'volcanic-cracks-warm',
            [11] = 'volcanic-folds',
            [12] = 'volcanic-folds-flat',
            [13] = 'volcanic-folds-warm',
            [14] = 'volcanic-jagged-ground',
            [15] = 'volcanic-pumice-stones',
            [16] = 'volcanic-smooth-stone',
            [17] = 'volcanic-smooth-stone-warm',
            --[18] = 'lava',
            --[19] = 'lava-hot',
        },
        ['start'] = start_value,
        ['weight'] = 1,
        ['ratios'] = {{resource = b.resource(b.full_shape, 'coal', value), weight = 1}}
    },
    {
        name = 'copper-ore',
        ['tiles'] = {
            [1] = 'fulgoran-conduit',
            [2] = 'fulgoran-dunes',
            [3] = 'fulgoran-dust',
            [4] = 'fulgoran-machinery',
            [5] = 'fulgoran-paving',
            [6] = 'fulgoran-rock',
            [7] = 'fulgoran-sand',
            [8] = 'fulgoran-walls',
            [9] = 'oil-ocean-deep',
            [10] = 'oil-ocean-shallow',
        },
        ['start'] = start_value,
        ['weight'] = 1,
        ['ratios'] = {{resource = b.resource(b.full_shape, 'coal', value), weight = 1}}
    },
    {
        name = 'iron-ore',
        ['tiles'] = {
            [1] = 'ammoniacal-ocean',
            [2] = 'ammoniacal-ocean-2',
            [3] = 'brash-ice',
            [4] = 'ice-rough',
            [5] = 'ice-smooth',
            [6] = 'snow-crests',
            [7] = 'snow-flat',
            [8] = 'snow-lumpy',
            [9] = 'snow-patchy',
        },
        ['start'] = start_value,
        ['weight'] = 1,
        ['ratios'] = {{resource = b.resource(b.full_shape, 'coal', value), weight = 1}}
    },
    {
        name = 'stone',
        ['tiles'] = {
            [1] = 'gleba-deep-lake',
            [2] = 'highland-dark-rock',
            [3] = 'highland-dark-rock-2',
            [4] = 'highland-yellow-rock',
            [5] = 'lowland-brown-blubber',
            [6] = 'lowland-cream-cauliflower',
            [7] = 'lowland-cream-cauliflower-2',
            [8] = 'lowland-cream-red',
            [9] = 'lowland-dead-skin',
            [10] = 'lowland-dead-skin-2',
            [11] = 'lowland-olive-blubber',
            [12] = 'lowland-olive-blubber-2',
            [13] = 'lowland-olive-blubber-3',
            [14] = 'lowland-pale-green',
            [15] = 'lowland-red-infection',
            [16] = 'lowland-red-vein',
            [17] = 'lowland-red-vein-2',
            [18] = 'lowland-red-vein-3',
            [19] = 'lowland-red-vein-4',
            [20] = 'lowland-red-vein-dead',
            [21] = 'midland-cracked-lichen',
            [22] = 'midland-cracked-lichen-dark',
            [23] = 'midland-cracked-lichen-dull',
            [24] = 'midland-turquoise-bark',
            [25] = 'midland-turquoise-bark-2',
            [26] = 'midland-yellow-crust',
            [27] = 'midland-yellow-crust-2',
            [28] = 'midland-yellow-crust-3',
            [29] = 'midland-yellow-crust-4',
            [30] = 'natural-jellynut-soil',
            [31] = 'natural-yumako-soil',
            [32] = 'pit-rock',
            [33] = 'wetland-blue-slime',
            [34] = 'wetland-dead-skin',
            [35] = 'wetland-green-slime',
            [36] = 'wetland-jellynut',
            [37] = 'wetland-light-dead-skin',
            [38] = 'wetland-light-green-slime',
            [39] = 'wetland-pink-tentacle',
            [40] = 'wetland-red-tentacle',
            [41] = 'wetland-yumako',
        },
        ['start'] = start_value,
        ['weight'] = 1,
        ['ratios'] = {{resource = b.resource(b.full_shape, 'coal', value), weight = 1}}
    }
}