local ob = require 'map_gen.maps.crash_site.outpost_builder'

return ob.make_1_way {
    turret = {callback = ob.refill_artillery_turret_callback, data = ob.artillery_shell_ammo},
    [1] = {tile = 'refined-concrete'},
    [2] = {tile = 'refined-concrete'},
    [3] = {tile = 'refined-concrete'},
    [4] = {tile = 'refined-concrete'},
    [5] = {tile = 'refined-concrete'},
    [6] = {tile = 'refined-concrete'},
    [7] = {tile = 'refined-concrete'},
    [8] = {entity = {name = 'artillery-turret', callback = 'turret'}, tile = 'refined-concrete'},
    [9] = {tile = 'refined-concrete'},
    [10] = {tile = 'refined-concrete'},
    [11] = {entity = {name = 'artillery-turret', callback = 'turret', direction = 2}, tile = 'refined-concrete'},
    [12] = {tile = 'refined-concrete'},
    [13] = {tile = 'refined-concrete'},
    [14] = {tile = 'refined-concrete'},
    [15] = {tile = 'refined-concrete'},
    [16] = {tile = 'refined-concrete'},
    [17] = {tile = 'refined-concrete'},
    [18] = {tile = 'refined-concrete'},
    [19] = {tile = 'refined-concrete'},
    [20] = {tile = 'refined-concrete'},
    [21] = {tile = 'refined-concrete'},
    [22] = {tile = 'refined-concrete'},
    [23] = {tile = 'refined-concrete'},
    [24] = {tile = 'refined-concrete'},
    [25] = {tile = 'refined-concrete'},
    [26] = {entity = {name = 'artillery-turret', callback = 'turret', direction = 6}, tile = 'refined-concrete'},
    [27] = {tile = 'refined-concrete'},
    [28] = {tile = 'refined-concrete'},
    [29] = {entity = {name = 'artillery-turret', callback = 'turret', direction = 4}, tile = 'refined-concrete'},
    [30] = {tile = 'refined-concrete'},
    [31] = {tile = 'refined-concrete'},
    [32] = {tile = 'refined-concrete'},
    [33] = {tile = 'refined-concrete'},
    [34] = {tile = 'refined-concrete'},
    [35] = {tile = 'refined-concrete'},
    [36] = {tile = 'refined-concrete'}
}
