local ob = require 'map_gen.maps.crash_site.outpost_builder'

local walls = ob.make_walls{
    ob.make_4_way {
        force = 'player',
        [1] = {entity = {name = 'stone-wall'}},
        [2] = {entity = {name = 'stone-wall'}},
        [3] = {entity = {name = 'stone-wall'}},
        [4] = {entity = {name = 'stone-wall'}},
        [5] = {entity = {name = 'stone-wall'}},
        [6] = {entity = {name = 'stone-wall'}},
        [7] = {tile = 'stone-path'},
        [8] = {tile = 'stone-path'},
        [9] = {tile = 'stone-path'},
        [10] = {tile = 'stone-path'},
        [11] = {tile = 'stone-path'},
        [12] = {tile = 'stone-path'},
        [13] = {tile = 'stone-path'},
        [14] = {tile = 'stone-path'},
        [15] = {tile = 'stone-path'},
        [16] = {tile = 'stone-path'},
        [17] = {tile = 'stone-path'},
        [18] = {tile = 'stone-path'},
        [19] = {tile = 'stone-path'},
        [20] = {tile = 'stone-path'},
        [21] = {tile = 'stone-path'},
        [22] = {tile = 'stone-path'},
        [23] = {tile = 'stone-path'},
        [24] = {tile = 'stone-path'},
        [25] = {tile = 'stone-path'},
        [26] = {tile = 'stone-path'},
        [27] = {tile = 'stone-path'},
        [28] = {tile = 'stone-path'},
        [29] = {tile = 'stone-path'},
        [30] = {tile = 'stone-path'},
        [31] = {tile = 'stone-path'},
        [32] = {tile = 'stone-path'},
        [33] = {tile = 'stone-path'},
        [34] = {tile = 'stone-path'},
        [35] = {tile = 'stone-path'},
        [36] = {tile = 'stone-path'}
    },
    ob.make_4_way {
        force = 'player',
        [1] = {entity = {name = 'stone-wall'}},
        [2] = {entity = {name = 'stone-wall'}},
        [3] = {entity = {name = 'stone-wall'}},
        [4] = {entity = {name = 'stone-wall'}},
        [5] = {entity = {name = 'stone-wall'}},
        [6] = {entity = {name = 'stone-wall'}},
        [7] = {entity = {name = 'stone-wall'}},
        [8] = {tile = 'stone-path'},
        [9] = {tile = 'stone-path'},
        [10] = {tile = 'stone-path'},
        [11] = {tile = 'stone-path'},
        [12] = {tile = 'stone-path'},
        [13] = {entity = {name = 'stone-wall'}},
        [14] = {tile = 'stone-path'},
        [15] = {tile = 'stone-path'},
        [16] = {tile = 'stone-path'},
        [17] = {tile = 'stone-path'},
        [18] = {tile = 'stone-path'},
        [19] = {entity = {name = 'stone-wall'}},
        [20] = {tile = 'stone-path'},
        [21] = {tile = 'stone-path'},
        [22] = {tile = 'stone-path'},
        [23] = {tile = 'stone-path'},
        [24] = {tile = 'stone-path'},
        [25] = {entity = {name = 'stone-wall'}},
        [26] = {tile = 'stone-path'},
        [27] = {tile = 'stone-path'},
        [28] = {tile = 'stone-path'},
        [29] = {tile = 'stone-path'},
        [30] = {tile = 'stone-path'},
        [31] = {entity = {name = 'stone-wall'}},
        [32] = {tile = 'stone-path'},
        [33] = {tile = 'stone-path'},
        [34] = {tile = 'stone-path'},
        [35] = {tile = 'stone-path'},
        [36] = {tile = 'stone-path'}
    },
    ob.make_4_way {
        force = 'player',
        [1] = {entity = {name = 'stone-wall'}},
        [2] = {tile = 'stone-path'},
        [3] = {tile = 'stone-path'},
        [4] = {tile = 'stone-path'},
        [5] = {tile = 'stone-path'},
        [6] = {tile = 'stone-path'},
        [7] = {tile = 'stone-path'},
        [8] = {tile = 'stone-path'},
        [9] = {tile = 'stone-path'},
        [10] = {tile = 'stone-path'},
        [11] = {tile = 'stone-path'},
        [12] = {tile = 'stone-path'},
        [13] = {tile = 'stone-path'},
        [14] = {tile = 'stone-path'},
        [15] = {tile = 'stone-path'},
        [16] = {tile = 'stone-path'},
        [17] = {tile = 'stone-path'},
        [18] = {tile = 'stone-path'},
        [19] = {tile = 'stone-path'},
        [20] = {tile = 'stone-path'},
        [21] = {tile = 'stone-path'},
        [22] = {tile = 'stone-path'},
        [23] = {tile = 'stone-path'},
        [24] = {tile = 'stone-path'},
        [25] = {tile = 'stone-path'},
        [26] = {tile = 'stone-path'},
        [27] = {tile = 'stone-path'},
        [28] = {tile = 'stone-path'},
        [29] = {tile = 'stone-path'},
        [30] = {tile = 'stone-path'},
        [31] = {tile = 'stone-path'},
        [32] = {tile = 'stone-path'},
        [33] = {tile = 'stone-path'},
        [34] = {tile = 'stone-path'},
        [35] = {tile = 'stone-path'},
        [36] = {tile = 'stone-path'}
    }
}

local bases = {
    ob.make_1_way {
        [1] = {tile = 'stone-path'},
        [2] = {tile = 'stone-path'},
        [3] = {tile = 'stone-path'},
        [4] = {tile = 'stone-path'},
        [5] = {tile = 'stone-path'},
        [6] = {tile = 'stone-path'},
        [7] = {tile = 'stone-path'},
        [8] = {tile = 'stone-path'},
        [9] = {tile = 'stone-path'},
        [10] = {tile = 'stone-path'},
        [11] = {tile = 'stone-path'},
        [12] = {tile = 'stone-path'},
        [13] = {tile = 'stone-path'},
        [14] = {tile = 'stone-path'},
        [15] = {tile = 'stone-path'},
        [16] = {tile = 'stone-path'},
        [17] = {tile = 'stone-path'},
        [18] = {tile = 'stone-path'},
        [19] = {tile = 'stone-path'},
        [20] = {tile = 'stone-path'},
        [21] = {tile = 'stone-path'},
        [22] = {tile = 'stone-path'},
        [23] = {tile = 'stone-path'},
        [24] = {tile = 'stone-path'},
        [25] = {tile = 'stone-path'},
        [26] = {tile = 'stone-path'},
        [27] = {tile = 'stone-path'},
        [28] = {tile = 'stone-path'},
        [29] = {tile = 'stone-path'},
        [30] = {tile = 'stone-path'},
        [31] = {tile = 'stone-path'},
        [32] = {tile = 'stone-path'},
        [33] = {tile = 'stone-path'},
        [34] = {tile = 'stone-path'},
        [35] = {tile = 'stone-path'},
        [36] = {tile = 'stone-path'}
    }
}

return {
    settings = {
        blocks = 18,
        variance = 3,
        min_step = 2,
        max_level = 2
    },
    walls = {walls},
    bases = {bases}
}
